# Generated by Django 4.0.3 on 2023-08-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
